// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY8jJegffNgJscTlghy9a18dqOFgWzwV0',
    appId: '1:809187945396:web:7842601f5271d1d48e60e1',
    messagingSenderId: '809187945396',
    projectId: 'petapp-d5368',
    authDomain: 'petapp-d5368.firebaseapp.com',
    storageBucket: 'petapp-d5368.firebasestorage.app',
    measurementId: 'G-WQPXNRQX1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQZvS6hDLbt7nxhXg_r9tJgTMifDokcKg',
    appId: '1:809187945396:android:bd7d56a12201da368e60e1',
    messagingSenderId: '809187945396',
    projectId: 'petapp-d5368',
    storageBucket: 'petapp-d5368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm-0DlmCfMtu3oqq3e5ghFcx0YIjWcGsY',
    appId: '1:809187945396:ios:8ef21b8452d8d0b38e60e1',
    messagingSenderId: '809187945396',
    projectId: 'petapp-d5368',
    storageBucket: 'petapp-d5368.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm-0DlmCfMtu3oqq3e5ghFcx0YIjWcGsY',
    appId: '1:809187945396:ios:8ef21b8452d8d0b38e60e1',
    messagingSenderId: '809187945396',
    projectId: 'petapp-d5368',
    storageBucket: 'petapp-d5368.firebasestorage.app',
    iosBundleId: 'com.example.petapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY8jJegffNgJscTlghy9a18dqOFgWzwV0',
    appId: '1:809187945396:web:8fe99c831d1b09eb8e60e1',
    messagingSenderId: '809187945396',
    projectId: 'petapp-d5368',
    authDomain: 'petapp-d5368.firebaseapp.com',
    storageBucket: 'petapp-d5368.firebasestorage.app',
    measurementId: 'G-VW2R1X4Z95',
  );
}
